### ISSUE TITLE
Gnome version

### ISSUE THREAD

**Issue by agreco** [hauleth/blame.vim#1]
Any chance of a Gnome terminal version?

**Comment by hauleth** [comment]
I believe that current version isn't 256 colours friendly (as I am `'termguicolors'` user). There is however a chance that I will try to make it as much 256 colours compatible. If you are asking about terminal colour scheme (not Vim, but terminal per se) then I do not think so, as I have no machine with GNOME Terminal at the moment, however it should be possible to translate `.Xresources` to GNOME Term scheme.

**Comment by agreco** [comment]
@hauleth thanks for the advice :+1:

**Comment by agreco** [comment]
@hauleth thanks for the advice :+1:
